SELECT
  `esgroadmap`.`targetsentences`.`Company` AS `Company`,
  `esgroadmap`.`targetsentences`.`companylist` AS `companylist`,
  `esgroadmap`.`targetsentences`.`Ticker(s)` AS `Ticker(s)`,
  `esgroadmap`.`targetsentences`.`PR Agency` AS `PR Agency`,
  `esgroadmap`.`targetsentences`.`Example 2020 company PR agency press release URL` AS `Example 2020 company PR agency press release URL`,
  `esgroadmap`.`targetsentences`.`Company Main Website URL` AS `Company Main Website URL`,
  `esgroadmap`.`targetsentences`.`Company press release site URL` AS `Company press release site URL`,
  `esgroadmap`.`targetsentences`.`Country` AS `Country`,
  `esgroadmap`.`targetsentences`.`sector code #1 (NAICS)` AS `sector code #1 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector name #1 (NAICS)` AS `sector name #1 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector code #2 (NAICS)` AS `sector code #2 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector name #2 (NAICS)` AS `sector name #2 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector code #3 (NAICS)` AS `sector code #3 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector name #3 (NAICS)` AS `sector name #3 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector code #4 (NAICS)` AS `sector code #4 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector name #4 (NAICS)` AS `sector name #4 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector code #5 (NAICS)` AS `sector code #5 (NAICS)`,
  `esgroadmap`.`targetsentences`.`sector name #5 (NAICS)` AS `sector name #5 (NAICS)`,
  `esgroadmap`.`targetsentences`.`S&P500member` AS `S&P500member`,
  `esgroadmap`.`targetsentences`.`Russell 1000 member` AS `Russell 1000 member`,
  `esgroadmap`.`targetsentences`.`emails` AS `emails`,
  `esgroadmap`.`targetsentences`.`full_text` AS `full_text`,
  `esgroadmap`.`targetsentences`.`Source link` AS `Source link`,
  `esgroadmap`.`targetsentences`.`pr_site` AS `pr_site`,
  `esgroadmap`.`targetsentences`.`release_date` AS `release_date`,
  `esgroadmap`.`targetsentences`.`source` AS `source`,
  `esgroadmap`.`targetsentences`.`ticker` AS `ticker`,
  `esgroadmap`.`targetsentences`.`title` AS `title`,
  `esgroadmap`.`targetsentences`.`ArticleTargetYear` AS `ArticleTargetYear`,
  `esgroadmap`.`targetsentences`.`PressReleaseFullCleanstep1` AS `PressReleaseFullCleanstep1`,
  `esgroadmap`.`targetsentences`.`PressReleaseFullClean` AS `PressReleaseFullClean`,
  `esgroadmap`.`targetsentences`.`Source date` AS `Source date`,
  `esgroadmap`.`targetsentences`.`PressReleaseYear` AS `PressReleaseYear`,
  `esgroadmap`.`targetsentences`.`PressReleaseMonth` AS `PressReleaseMonth`,
  `esgroadmap`.`targetsentences`.`Target sentence` AS `Target sentence`,
  `esgroadmap`.`targetsentences`.`SentenceTargetYear` AS `SentenceTargetYear`,
  `esgroadmap`.`targetsentences`.`Targetyear(s)` AS `Targetyear(s)`,
  `esgroadmap`.`targetsentences`.`sentence-carbon` AS `sentence-carbon`,
  `esgroadmap`.`targetsentences`.`sentence-gender` AS `sentence-gender`,
  `esgroadmap`.`targetsentences`.`sentence-renewables` AS `sentence-renewables`,
  `esgroadmap`.`targetsentences`.`sentence-suppliers` AS `sentence-suppliers`,
  `esgroadmap`.`targetsentences`.`sentence-water` AS `sentence-water`,
  `esgroadmap`.`targetsentences`.`Primarysource` AS `Primarysource`
FROM
  `esgroadmap`.`targetsentences`